<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.4 | Adapted by Montepage

$CONF['sql_user']=htmlspecialchars_decode("sigepe_admin");
$CONF['sql_host']=htmlspecialchars_decode("localhost");
$CONF['sql_db']=htmlspecialchars_decode("sigepe_bd");
$CONF['ftp_use']=htmlspecialchars_decode("0");
$CONF['email_use']=htmlspecialchars_decode("1");
$CONF['sitename']=htmlspecialchars_decode("example.com");
$CONF['lang']=htmlspecialchars_decode("portugues");
$CONF['import_error']=htmlspecialchars_decode("1");
$CONF['no_login']=htmlspecialchars_decode("0");
$CONF['login']=htmlspecialchars_decode("0");
$CONF['dir_backup']=htmlspecialchars_decode("0");
$CONF['dir_rec']=htmlspecialchars_decode("1");
$CONF['email']=htmlspecialchars_decode("raphael.a.a.p@gmail.com");
$CONF['ftp_pasv']=htmlspecialchars_decode("1");
$CONF['ftp_del']=htmlspecialchars_decode("1");
$CONF['ftp_server']=htmlspecialchars_decode("example.com");
$CONF['ftp_user']=htmlspecialchars_decode("");
$CONF['ftp_port']=htmlspecialchars_decode("21");
$CONF['date']=htmlspecialchars_decode("%x %X");
$CONF['del_time']=htmlspecialchars_decode("5");
$CONF['del_number']=htmlspecialchars_decode("10");
$CONF['timelimit']=htmlspecialchars_decode("60");
$CONF['confirm']=htmlspecialchars_decode("1");
$CONF['stylesheet']=htmlspecialchars_decode("standard");
$CONF['ftp_path']=htmlspecialchars_decode("");
$CONF['ftp_passwd']=htmlspecialchars_decode("");
$CONF['sql_passwd']=htmlspecialchars_decode("002128");

$PMBP_SYS_VAR['last_scheduled']=htmlspecialchars_decode("1477611992");
$PMBP_SYS_VAR['this_login']=htmlspecialchars_decode("10/27/16 21:29:09 (IP: 201.57.199.130)");
$PMBP_SYS_VAR['last_login']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['dir_lists']=htmlspecialchars_decode("1");
$PMBP_SYS_VAR['memory_limit']=htmlspecialchars_decode("4000000");
$PMBP_SYS_VAR['except_tables']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['scheduled_debug']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['schedule_all_dbs']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['ftp_timeout']=htmlspecialchars_decode("10");
$PMBP_SYS_VAR['dir_email_backup']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['C_disable_config']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['C_disable_sqlquery']=htmlspecialchars_decode("0");
$PMBP_SYS_VAR['B_backup_chmod']=htmlspecialchars_decode("0700");
$PMBP_SYS_VAR['F_dbs']=htmlspecialchars_decode("sigepe_bd");
$PMBP_SYS_VAR['F_comment']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_tables']=htmlspecialchars_decode("on");
$PMBP_SYS_VAR['F_data']=htmlspecialchars_decode("on");
$PMBP_SYS_VAR['F_drop']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_compression']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_ftp_dirs']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_ftp_dirs_2']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_packed']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['F_updates']=htmlspecialchars_decode("1");
$PMBP_SYS_VAR['F_ffadd']=htmlspecialchars_decode("1");
$PMBP_SYS_VAR['EXS_scheduled_file']=htmlspecialchars_decode("???.php");
$PMBP_SYS_VAR['EXS_scheduled_dir']=htmlspecialchars_decode("");
$PMBP_SYS_VAR['EXS_period']=htmlspecialchars_decode("/4");
$PMBP_SYS_VAR['security_key']=htmlspecialchars_decode("f21c0d5252b67c94096d558faea6368a");

?>